import type { IlytatTheme } from '../../types'

export const luxuryThemes: IlytatTheme[] = [
    {
        id: 'luxury-gold-black',
        name: 'Gold & Black',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#000000',
            '--bg-secondary': '#111111',
            '--bg-tertiary': '#222222',
            '--app-bg': 'radial-gradient(circle at top right, #222222, #000000)', // Rich radial for luxury
            '--text-primary': '#D4AF37', // Gold
            '--text-secondary': '#AA8C2C',
            '--text-tertiary': '#80691F',
            '--accent-primary': '#D4AF37',
            '--accent-secondary': '#FFD700',
            '--border-color': '#333333',
            '--glass-bg': 'rgba(0, 0, 0, 0.9)',
            '--glass-border': 'rgba(212, 175, 55, 0.3)',
            '--glass-shadow': '0 10px 30px rgba(0, 0, 0, 0.8)'
        }
    },
    {
        id: 'luxury-silver-snow',
        name: 'Sterling Silver',
        category: 'luxury',
        isDark: false,
        colors: {
            '--bg-primary': '#F5F5F7',
            '--bg-secondary': '#E5E5EA',
            '--bg-tertiary': '#D1D1D6',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#1C1C1E',
            '--text-secondary': '#3A3A3C',
            '--text-tertiary': '#8E8E93',
            '--accent-primary': '#8E8E93',
            '--accent-secondary': '#AEAEB2',
            '--border-color': '#C7C7CC',
            '--glass-bg': 'rgba(245, 245, 247, 0.8)',
            '--glass-border': 'rgba(142, 142, 147, 0.2)',
            '--glass-shadow': '0 10px 30px rgba(0, 0, 0, 0.05)'
        }
    },
    {
        id: 'luxury-royal-purple',
        name: 'Royal Purple',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#120024',
            '--bg-secondary': '#240046',
            '--bg-tertiary': '#3C006B',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#E0AAFF',
            '--text-secondary': '#C77DFF',
            '--text-tertiary': '#9D4EDD',
            '--accent-primary': '#FFD700', // Gold accent
            '--accent-secondary': '#E0AAFF',
            '--border-color': '#3C006B',
            '--glass-bg': 'rgba(18, 0, 36, 0.9)',
            '--glass-border': 'rgba(255, 215, 0, 0.2)',
            '--glass-shadow': '0 10px 30px rgba(0, 0, 0, 0.5)'
        }
    },
    {
        id: 'luxury-emerald-gold',
        name: 'Emerald & Gold',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#011c13',
            '--bg-secondary': '#022c1e',
            '--bg-tertiary': '#03412c',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#d4af37',
            '--text-secondary': '#c5a028',
            '--text-tertiary': '#a6851f',
            '--accent-primary': '#d4af37',
            '--accent-secondary': '#50c878', // Emerald green
            '--border-color': '#03412c',
            '--glass-bg': 'rgba(1, 28, 19, 0.95)',
            '--glass-border': 'rgba(212, 175, 55, 0.2)',
            '--glass-shadow': '0 10px 30px rgba(0, 0, 0, 0.6)'
        }
    },
    {
        id: 'luxury-platinum',
        name: 'Platinum',
        category: 'luxury',
        isDark: false,
        colors: {
            '--bg-primary': '#e3e4e6',
            '--bg-secondary': '#d7d8db',
            '--bg-tertiary': '#c0c2c8',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#1a1b1d',
            '--text-secondary': '#46494f',
            '--text-tertiary': '#737780',
            '--accent-primary': '#5f636b',
            '--accent-secondary': '#8c9099',
            '--border-color': '#c0c2c8',
            '--glass-bg': 'rgba(227, 228, 230, 0.8)',
            '--glass-border': 'rgba(95, 99, 107, 0.15)',
            '--glass-shadow': '0 8px 25px rgba(0, 0, 0, 0.08)'
        }
    },
    {
        id: 'luxury-champagne',
        name: 'Champagne',
        category: 'luxury',
        isDark: false,
        colors: {
            '--bg-primary': '#f7e7ce',
            '--bg-secondary': '#f1dcb8',
            '--bg-tertiary': '#eacc9f',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#4a3b2a',
            '--text-secondary': '#6b5740',
            '--text-tertiary': '#8c7559',
            '--accent-primary': '#c9a676',
            '--accent-secondary': '#e0c092',
            '--border-color': '#eacc9f',
            '--glass-bg': 'rgba(247, 231, 206, 0.85)',
            '--glass-border': 'rgba(201, 166, 118, 0.2)',
            '--glass-shadow': '0 5px 15px rgba(74, 59, 42, 0.05)'
        }
    },
    {
        id: 'luxury-obsidian-gold',
        name: 'Obsidian & Gold',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#0b0b0b',
            '--bg-secondary': '#161616',
            '--bg-tertiary': '#212121',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#cfb53b', // pale gold
            '--text-secondary': '#a89028',
            '--text-tertiary': '#7a6818',
            '--accent-primary': '#cfb53b',
            '--accent-secondary': '#e6cp6e',
            '--border-color': '#212121',
            '--glass-bg': 'rgba(11, 11, 11, 0.95)',
            '--glass-border': 'rgba(207, 181, 59, 0.15)',
            '--glass-shadow': '0 10px 40px rgba(0, 0, 0, 0.9)'
        }
    },
    {
        id: 'luxury-midnight-silk',
        name: 'Midnight Silk',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#191970', // midnight blue
            '--bg-secondary': '#14145a',
            '--bg-tertiary': '#0F0F44',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#f8f8ff', // ghost white
            '--text-secondary': '#dcdcdc',
            '--text-tertiary': '#b0c4de',
            '--accent-primary': '#c0c0c0', // silver
            '--accent-secondary': '#a9a9a9',
            '--border-color': '#0F0F44',
            '--glass-bg': 'rgba(25, 25, 112, 0.9)',
            '--glass-border': 'rgba(192, 192, 192, 0.15)',
            '--glass-shadow': '0 8px 30px rgba(0, 0, 0, 0.4)'
        }
    },
    {
        id: 'luxury-rose-gold',
        name: 'Rose Gold',
        category: 'luxury',
        isDark: false,
        colors: {
            '--bg-primary': '#fff0f5',
            '--bg-secondary': '#fde2e9',
            '--bg-tertiary': '#fad3dd',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#8e5968',
            '--text-secondary': '#b76e79',
            '--text-tertiary': '#d48c96',
            '--accent-primary': '#b76e79', // rose gold
            '--accent-secondary': '#eec4cd',
            '--border-color': '#fad3dd',
            '--glass-bg': 'rgba(255, 240, 245, 0.85)',
            '--glass-border': 'rgba(183, 110, 121, 0.2)',
            '--glass-shadow': '0 5px 15px rgba(183, 110, 121, 0.1)'
        }
    },
    {
        id: 'luxury-marble',
        name: 'White Marble',
        category: 'luxury',
        isDark: false,
        colors: {
            '--bg-primary': '#fdfbf9',
            '--bg-secondary': '#f3f1ef',
            '--bg-tertiary': '#e6e4e2',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#2b2b2b',
            '--text-secondary': '#4a4a4a',
            '--text-tertiary': '#6e6e6e',
            '--accent-primary': '#8c8c8c',
            '--accent-secondary': '#a6a6a6',
            '--border-color': '#e6e4e2',
            '--glass-bg': 'rgba(253, 251, 249, 0.9)',
            '--glass-border': 'rgba(0, 0, 0, 0.05)',
            '--glass-shadow': '0 4px 10px rgba(0, 0, 0, 0.05)'
        }
    },
    {
        id: 'luxury-rich-mahogany',
        name: 'Rich Mahogany',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#420d09',
            '--bg-secondary': '#5d1a15',
            '--bg-tertiary': '#782721',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#f4e4bc', // cream
            '--text-secondary': '#e0cda0',
            '--text-tertiary': '#cbb684',
            '--accent-primary': '#cbb684', // antique gold
            '--accent-secondary': '#f4e4bc',
            '--border-color': '#782721',
            '--glass-bg': 'rgba(66, 13, 9, 0.95)',
            '--glass-border': 'rgba(203, 182, 132, 0.15)',
            '--glass-shadow': '0 8px 30px rgba(0, 0, 0, 0.6)'
        }
    },
    {
        id: 'luxury-sapphire',
        name: 'Dark Sapphire',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#082567',
            '--bg-secondary': '#0b328a',
            '--bg-tertiary': '#103fad',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#e6f2ff',
            '--text-secondary': '#b3d9ff',
            '--text-tertiary': '#80bfff',
            '--accent-primary': '#4facfe',
            '--accent-secondary': '#00f2fe',
            '--border-color': '#103fad',
            '--glass-bg': 'rgba(8, 37, 103, 0.9)',
            '--glass-border': 'rgba(79, 172, 254, 0.2)',
            '--glass-shadow': '0 8px 25px rgba(0, 0, 0, 0.4)'
        }
    },
    {
        id: 'luxury-pearl',
        name: 'Mother of Pearl',
        category: 'luxury',
        isDark: false,
        colors: {
            '--bg-primary': '#fcfcfc',
            '--bg-secondary': '#f2f2f2',
            '--bg-tertiary': '#e6e6e6',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#333333',
            '--text-secondary': '#666666',
            '--text-tertiary': '#999999',
            '--accent-primary': '#e0ffff', // light cyan hint
            '--accent-secondary': '#ffe4e1', // misty rose hint
            '--border-color': '#e6e6e6',
            '--glass-bg': 'linear-gradient(135deg, rgba(255, 255, 255, 0.8) 0%, rgba(240, 255, 255, 0.8) 100%)',
            '--glass-border': 'rgba(255, 255, 255, 0.6)',
            '--glass-shadow': '0 5px 15px rgba(0, 0, 0, 0.03)'
        }
    },
    {
        id: 'luxury-bronze',
        name: 'Aged Bronze',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#3b2f2f',
            '--bg-secondary': '#4e3e3e',
            '--bg-tertiary': '#614d4d',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#cd7f32',
            '--text-secondary': '#b87333',
            '--text-tertiary': '#a0522d',
            '--accent-primary': '#cd7f32',
            '--accent-secondary': '#d2691e',
            '--border-color': '#614d4d',
            '--glass-bg': 'rgba(59, 47, 47, 0.95)',
            '--glass-border': 'rgba(205, 127, 50, 0.15)',
            '--glass-shadow': '0 5px 20px rgba(0, 0, 0, 0.5)'
        }
    },
    {
        id: 'luxury-velvet',
        name: 'Red Velvet',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#330000',
            '--bg-secondary': '#4d0000',
            '--bg-tertiary': '#660000',
            '--app-bg': 'radial-gradient(circle at top right, var(--bg-tertiary), var(--bg-primary))',
            '--text-primary': '#ffcccc',
            '--text-secondary': '#ff9999',
            '--text-tertiary': '#ff6666',
            '--accent-primary': '#ffc0cb', // pink accent
            '--accent-secondary': '#ffb6c1',
            '--border-color': '#660000',
            '--glass-bg': 'rgba(51, 0, 0, 0.95)',
            '--glass-border': 'rgba(255, 192, 203, 0.1)',
            '--glass-shadow': '0 8px 25px rgba(0, 0, 0, 0.5)'
        }
    },
    {
        id: 'gen-platinum-luxury',
        name: 'Platinum',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#3a1212',
            '--bg-tertiary': '#681818',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#09f680',
            '--accent-secondary': '#0980f6',
            '--border-color': '#681818',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #681818, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-diamond-luxury',
        name: 'Diamond',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#152637',
            '--bg-tertiary': '#1d4062',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#eb1414',
            '--accent-secondary': '#ebeb14',
            '--border-color': '#1d4062',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #1d4062, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-ruby-luxury',
        name: 'Ruby',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#331919',
            '--bg-tertiary': '#5c2424',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#21de80',
            '--accent-secondary': '#2180de',
            '--border-color': '#5c2424',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #5c2424, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-emerald-luxury',
        name: 'Emerald',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#2c2920',
            '--bg-tertiary': '#50482f',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#38a3c7',
            '--accent-secondary': '#5c38c7',
            '--border-color': '#50482f',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #50482f, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-sapphire-luxury',
        name: 'Sapphire',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#192634',
            '--bg-tertiary': '#23405c',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#df2020',
            '--accent-secondary': '#dfdf20',
            '--border-color': '#23405c',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #23405c, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-onyx-luxury',
        name: 'Onyx',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#2d123a',
            '--bg-tertiary': '#4d1868',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#cef609',
            '--accent-secondary': '#09f630',
            '--border-color': '#4d1868',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #4d1868, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-pearl-luxury',
        name: 'Pearl',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#12263a',
            '--bg-tertiary': '#184068',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#f60909',
            '--accent-secondary': '#f6f609',
            '--border-color': '#184068',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #184068, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-champagne-luxury',
        name: 'Champagne',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#2d2020',
            '--bg-tertiary': '#512e2e',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#36c980',
            '--accent-secondary': '#3680c9',
            '--border-color': '#512e2e',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #512e2e, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-velvet-luxury',
        name: 'Velvet',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#1d2630',
            '--bg-tertiary': '#2a4056',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#d22d2d',
            '--accent-secondary': '#d2d22d',
            '--border-color': '#2a4056',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #2a4056, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-silk-luxury',
        name: 'Silk',
        category: 'luxury',
        isDark: true,
        colors: {
            '--bg-primary': '#050505',
            '--bg-secondary': '#2c1537',
            '--bg-tertiary': '#4b1d62',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#c7eb14',
            '--accent-secondary': '#14eb38',
            '--border-color': '#4b1d62',
            '--glass-bg': '#050505b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(circle at top right, #4b1d62, #050505), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    }
]
