import type { IlytatTheme } from '../../types'

export const minimalThemes: IlytatTheme[] = [
    {
        id: 'minimal-light',
        name: 'Minimal Light',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f9fafb',
            '--bg-tertiary': '#f3f4f6',
            '--app-bg': '#ffffff', // Minimal stays solid mostly
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#9ca3af',
            '--accent-primary': '#000000',
            '--accent-secondary': '#374151',
            '--border-color': '#e5e7eb',
            '--glass-bg': 'rgba(255, 255, 255, 0.9)',
            '--glass-border': 'rgba(0, 0, 0, 0.05)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-dark',
        name: 'Minimal Dark',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#000000',
            '--bg-secondary': '#111111',
            '--bg-tertiary': '#222222',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#ffffff',
            '--text-secondary': '#a1a1a1',
            '--text-tertiary': '#555555',
            '--accent-primary': '#ffffff',
            '--accent-secondary': '#d4d4d4',
            '--border-color': '#333333',
            '--glass-bg': 'rgba(0, 0, 0, 0.9)',
            '--glass-border': 'rgba(255, 255, 255, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-solar',
        name: 'Solar White',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#fdfbf7',
            '--bg-secondary': '#f7f3e8',
            '--bg-tertiary': '#efe5d0',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#2d2a26',
            '--text-secondary': '#5c5446',
            '--text-tertiary': '#9e9484',
            '--accent-primary': '#d1a34d',
            '--accent-secondary': '#e6c88b',
            '--border-color': '#e0d8c3',
            '--glass-bg': 'rgba(253, 251, 247, 0.9)',
            '--glass-border': 'rgba(209, 163, 77, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-midnight-blue',
        name: 'Midnight Blue Minimal',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#0f172a',
            '--bg-secondary': '#1e293b',
            '--bg-tertiary': '#334155',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#f1f5f9',
            '--text-secondary': '#cbd5e1',
            '--text-tertiary': '#94a3b8',
            '--accent-primary': '#38bdf8',
            '--accent-secondary': '#7dd3fc',
            '--border-color': '#1e293b',
            '--glass-bg': 'rgba(15, 23, 42, 0.95)',
            '--glass-border': 'rgba(56, 189, 248, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-slate',
        name: 'Slate Minimal',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#f8fafc',
            '--bg-secondary': '#f1f5f9',
            '--bg-tertiary': '#e2e8f0',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#334155',
            '--text-secondary': '#475569',
            '--text-tertiary': '#94a3b8',
            '--accent-primary': '#475569',
            '--accent-secondary': '#64748b',
            '--border-color': '#cbd5e1',
            '--glass-bg': 'rgba(248, 250, 252, 0.9)',
            '--glass-border': 'rgba(0, 0, 0, 0.05)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-charcoal',
        name: 'Charcoal',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#18181b',
            '--bg-secondary': '#27272a',
            '--bg-tertiary': '#3f3f46',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#fafafa',
            '--text-secondary': '#d4d4d8',
            '--text-tertiary': '#a1a1aa',
            '--accent-primary': '#d4d4d8',
            '--accent-secondary': '#e4e4e7',
            '--border-color': '#27272a',
            '--glass-bg': 'rgba(24, 24, 27, 0.9)',
            '--glass-border': 'rgba(255, 255, 255, 0.05)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-beige',
        name: 'Soft Beige',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#fffbf0',
            '--bg-secondary': '#f7f1e3',
            '--bg-tertiary': '#ede6d5',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#4a4036',
            '--text-secondary': '#786b5f',
            '--text-tertiary': '#a3968b',
            '--accent-primary': '#8c7b6d',
            '--accent-secondary': '#b0a092',
            '--border-color': '#e6decb',
            '--glass-bg': 'rgba(255, 251, 240, 0.9)',
            '--glass-border': 'rgba(74, 64, 54, 0.05)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-forest',
        name: 'Deep Forest',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#052e16',
            '--bg-secondary': '#14532d',
            '--bg-tertiary': '#166534',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#f0fdf4',
            '--text-secondary': '#bbf7d0',
            '--text-tertiary': '#86efac',
            '--accent-primary': '#4ade80',
            '--accent-secondary': '#86efac',
            '--border-color': '#14532d',
            '--glass-bg': 'rgba(5, 46, 22, 0.9)',
            '--glass-border': 'rgba(74, 222, 128, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-lavender',
        name: 'Pale Lavender',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#faf5ff',
            '--bg-secondary': '#f3e8ff',
            '--bg-tertiary': '#e9d5ff',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#581c87',
            '--text-secondary': '#7e22ce',
            '--text-tertiary': '#a855f7',
            '--accent-primary': '#9333ea',
            '--accent-secondary': '#c084fc',
            '--border-color': '#f3e8ff',
            '--glass-bg': 'rgba(250, 245, 255, 0.9)',
            '--glass-border': 'rgba(147, 51, 234, 0.05)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-navy',
        name: 'Navy Blue',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#172554',
            '--bg-secondary': '#1e3a8a',
            '--bg-tertiary': '#1e40af',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#eff6ff',
            '--text-secondary': '#bfdbfe',
            '--text-tertiary': '#60a5fa',
            '--accent-primary': '#3b82f6',
            '--accent-secondary': '#60a5fa',
            '--border-color': '#1e3a8a',
            '--glass-bg': 'rgba(23, 37, 84, 0.9)',
            '--glass-border': 'rgba(59, 130, 246, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-mint',
        name: 'Mint Minimal',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#f0fdfa',
            '--bg-secondary': '#ccfbf1',
            '--bg-tertiary': '#99f6e4',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#134e4a',
            '--text-secondary': '#0f766e',
            '--text-tertiary': '#14b8a6',
            '--accent-primary': '#14b8a6',
            '--accent-secondary': '#2dd4bf',
            '--border-color': '#ccfbf1',
            '--glass-bg': 'rgba(240, 253, 250, 0.9)',
            '--glass-border': 'rgba(20, 184, 166, 0.05)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-cocoa',
        name: 'Cocoa Dark',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#2a1a14',
            '--bg-secondary': '#3f251b',
            '--bg-tertiary': '#553224',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#fdf2eb',
            '--text-secondary': '#d8bba9',
            '--text-tertiary': '#a68c7b',
            '--accent-primary': '#c9a58f',
            '--accent-secondary': '#e4ccbc',
            '--border-color': '#3f251b',
            '--glass-bg': 'rgba(42, 26, 20, 0.9)',
            '--glass-border': 'rgba(201, 165, 143, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-grayscale',
        name: 'True Grayscale',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#eeeeee',
            '--bg-secondary': '#dddddd',
            '--bg-tertiary': '#cccccc',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#222222',
            '--text-secondary': '#444444',
            '--text-tertiary': '#777777',
            '--accent-primary': '#444444',
            '--accent-secondary': '#666666',
            '--border-color': '#d4d4d4',
            '--glass-bg': 'rgba(238, 238, 238, 0.9)',
            '--glass-border': 'rgba(0, 0, 0, 0.05)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-plum',
        name: 'Deep Plum',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#2e0f27',
            '--bg-secondary': '#4a153d',
            '--bg-tertiary': '#661b55',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#fce7f3',
            '--text-secondary': '#f9a8d4',
            '--text-tertiary': '#f472b6',
            '--accent-primary': '#ec4899',
            '--accent-secondary': '#f472b6',
            '--border-color': '#4a153d',
            '--glass-bg': 'rgba(46, 15, 39, 0.9)',
            '--glass-border': 'rgba(236, 72, 153, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'minimal-sky',
        name: 'Sky Blue Minimal',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#e0f2fe',
            '--bg-secondary': '#bae6fd',
            '--bg-tertiary': '#7dd3fc',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#0c4a6e',
            '--text-secondary': '#0369a1',
            '--text-tertiary': '#0284c7',
            '--accent-primary': '#0284c7',
            '--accent-secondary': '#38bdf8',
            '--border-color': '#bae6fd',
            '--glass-bg': 'rgba(224, 242, 254, 0.9)',
            '--glass-border': 'rgba(2, 132, 199, 0.05)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'gen-ghost-minimal',
        name: 'Ghost',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#1f1f1f',
            '--bg-secondary': '#2c2c2c',
            '--bg-tertiary': '#393939',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#90607a',
            '--accent-secondary': '#a77c93',
            '--border-color': '#393939',
            '--glass-bg': '#1f1f1fb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#1f1f1f',
        },
    },
    {
        id: 'gen-ash-minimal',
        name: 'Ash',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#f6f5f3',
            '--bg-secondary': '#efeeea',
            '--bg-tertiary': '#e9e6e2',
            '--text-primary': '#3e362d',
            '--text-secondary': '#796958',
            '--text-tertiary': '#ab9c8c',
            '--accent-primary': '#95846f',
            '--accent-secondary': '#ab9d8c',
            '--border-color': '#e9e6e2',
            '--glass-bg': '#f6f5f399',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': '#f6f5f3',
        },
    },
    {
        id: 'gen-dust-minimal',
        name: 'Dust',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#1f1f1f',
            '--bg-secondary': '#2c2c2c',
            '--bg-tertiary': '#393939',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#857f6b',
            '--accent-secondary': '#9d9886',
            '--border-color': '#393939',
            '--glass-bg': '#1f1f1fb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#1f1f1f',
        },
    },
    {
        id: 'gen-mist-minimal',
        name: 'Mist',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#f6f5f5',
            '--bg-secondary': '#efeded',
            '--bg-tertiary': '#e8e5e5',
            '--text-primary': '#393533',
            '--text-secondary': '#6f6763',
            '--text-tertiary': '#a29a97',
            '--accent-primary': '#8a807b',
            '--accent-secondary': '#a29a96',
            '--border-color': '#e8e5e5',
            '--glass-bg': '#f6f5f599',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': '#f6f5f5',
        },
    },
    {
        id: 'gen-fog-minimal',
        name: 'Fog',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#e7e6ea',
            '--bg-secondary': '#dfdee3',
            '--bg-tertiary': '#d7d5dc',
            '--text-primary': '#27252d',
            '--text-secondary': '#585365',
            '--text-tertiary': '#8a849a',
            '--accent-primary': '#6f6a81',
            '--accent-secondary': '#89849a',
            '--border-color': '#d7d5dc',
            '--glass-bg': '#e7e6ea99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': '#e7e6ea',
        },
    },
    {
        id: 'gen-snow-minimal',
        name: 'Snow',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#141414',
            '--bg-secondary': '#212121',
            '--bg-tertiary': '#2e2e2e',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#9e7370',
            '--accent-secondary': '#b3918e',
            '--border-color': '#2e2e2e',
            '--glass-bg': '#141414b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#141414',
        },
    },
    {
        id: 'gen-cloud-minimal',
        name: 'Cloud',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#262626',
            '--bg-secondary': '#333333',
            '--bg-tertiary': '#404040',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#8ca69e',
            '--accent-secondary': '#a9bcb6',
            '--border-color': '#404040',
            '--glass-bg': '#262626b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#262626',
        },
    },
    {
        id: 'gen-bone-minimal',
        name: 'Bone',
        category: 'minimal',
        isDark: true,
        colors: {
            '--bg-primary': '#0f0f0f',
            '--bg-secondary': '#1c1c1c',
            '--bg-tertiary': '#292929',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#828282',
            '--accent-secondary': '#9b9b9b',
            '--border-color': '#292929',
            '--glass-bg': '#0f0f0fb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#0f0f0f',
        },
    },
    {
        id: 'gen-sand-minimal',
        name: 'Sand',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#efebec',
            '--bg-secondary': '#e8e2e4',
            '--bg-tertiary': '#e1dadc',
            '--text-primary': '#33292a',
            '--text-secondary': '#6c5659',
            '--text-tertiary': '#a0888b',
            '--accent-primary': '#876e70',
            '--accent-secondary': '#9f898b',
            '--border-color': '#e1dadc',
            '--glass-bg': '#efebec99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': '#efebec',
        },
    },
    {
        id: 'gen-stone-minimal',
        name: 'Stone',
        category: 'minimal',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f7f7f7',
            '--bg-tertiary': '#f0f0f0',
            '--text-primary': '#172117',
            '--text-secondary': '#415d41',
            '--text-tertiary': '#6c986c',
            '--accent-primary': '#567b56',
            '--accent-secondary': '#6c986c',
            '--border-color': '#f0f0f0',
            '--glass-bg': '#ffffff99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': '#ffffff',
        },
    }
]
