import type { IlytatTheme } from '../../types'

export const glassThemes: IlytatTheme[] = [
    {
        id: 'glass-classic-light',
        name: 'Glass Classic (Light)',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#f0f4f8',
            '--bg-secondary': '#ffffff',
            '--bg-tertiary': '#e2e8f0',
            '--app-bg': 'linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%)', // Subtle gradient for glass
            '--text-primary': '#1e293b',
            '--text-secondary': '#475569',
            '--text-tertiary': '#94a3b8',
            '--accent-primary': '#3b82f6',
            '--accent-secondary': '#60a5fa',
            '--border-color': 'rgba(255, 255, 255, 0.4)',
            '--glass-bg': 'rgba(255, 255, 255, 0.7)',
            '--glass-border': 'rgba(255, 255, 255, 0.5)',
            '--glass-shadow': '0 8px 32px 0 rgba(31, 38, 135, 0.15)'
        }
    },
    {
        id: 'glass-classic-dark',
        name: 'Glass Classic (Dark)',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#0f172a',
            '--bg-secondary': '#1e293b',
            '--bg-tertiary': '#334155',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#f8fafc',
            '--text-secondary': '#cbd5e1',
            '--text-tertiary': '#94a3b8',
            '--accent-primary': '#60a5fa',
            '--accent-secondary': '#3b82f6',
            '--border-color': 'rgba(255, 255, 255, 0.1)',
            '--glass-bg': 'rgba(30, 41, 59, 0.7)',
            '--glass-border': 'rgba(255, 255, 255, 0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.37)'
        }
    },
    {
        id: 'glass-frost-teal',
        name: 'Frosted Teal',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#f0fdfa',
            '--bg-secondary': '#ccfbf1',
            '--bg-tertiary': '#99f6e4',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#134e4a',
            '--text-secondary': '#115e59',
            '--text-tertiary': '#2dd4bf',
            '--accent-primary': '#14b8a6',
            '--accent-secondary': '#2dd4bf',
            '--border-color': 'rgba(20, 184, 166, 0.2)',
            '--glass-bg': 'rgba(240, 253, 250, 0.6)',
            '--glass-border': 'rgba(255, 255, 255, 0.6)',
            '--glass-shadow': '0 4px 20px 0 rgba(20, 184, 166, 0.1)'
        }
    },
    {
        id: 'glass-midnight-blur',
        name: 'Midnight Blur',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#020617',
            '--bg-secondary': '#0f172a',
            '--bg-tertiary': '#1e293b',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#e2e8f0',
            '--text-secondary': '#94a3b8',
            '--text-tertiary': '#64748b',
            '--accent-primary': '#6366f1',
            '--accent-secondary': '#818cf8',
            '--border-color': 'rgba(99, 102, 241, 0.2)',
            '--glass-bg': 'rgba(15, 23, 42, 0.5)',
            '--glass-border': 'rgba(99, 102, 241, 0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.5)'
        }
    },
    {
        id: 'glass-rose-quartz',
        name: 'Rose Quartz',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#fff1f2',
            '--bg-secondary': '#ffe4e6',
            '--bg-tertiary': '#fecdd3',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#881337',
            '--text-secondary': '#be123c',
            '--text-tertiary': '#fb7185',
            '--accent-primary': '#f43f5e',
            '--accent-secondary': '#fb7185',
            '--border-color': 'rgba(244, 63, 94, 0.2)',
            '--glass-bg': 'rgba(255, 241, 242, 0.65)',
            '--glass-border': 'rgba(255, 255, 255, 0.6)',
            '--glass-shadow': '0 4px 15px 0 rgba(244, 63, 94, 0.1)'
        }
    },
    {
        id: 'glass-obsidian',
        name: 'Obsidian Glass',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#000000',
            '--bg-secondary': '#111111',
            '--bg-tertiary': '#222222',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#ededed',
            '--text-secondary': '#a1a1a1',
            '--text-tertiary': '#555555',
            '--accent-primary': '#ffffff',
            '--accent-secondary': '#d4d4d4',
            '--border-color': 'rgba(255, 255, 255, 0.15)',
            '--glass-bg': 'rgba(0, 0, 0, 0.8)',
            '--glass-border': 'rgba(255, 255, 255, 0.1)',
            '--glass-shadow': '0 10px 40px 0 rgba(0, 0, 0, 0.8)'
        }
    },
    {
        id: 'glass-arctic',
        name: 'Arctic Ice',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#f0f9ff',
            '--bg-secondary': '#e0f2fe',
            '--bg-tertiary': '#bae6fd',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#0c4a6e',
            '--text-secondary': '#0369a1',
            '--text-tertiary': '#38bdf8',
            '--accent-primary': '#0ea5e9',
            '--accent-secondary': '#38bdf8',
            '--border-color': 'rgba(14, 165, 233, 0.2)',
            '--glass-bg': 'rgba(240, 249, 255, 0.6)',
            '--glass-border': 'rgba(255, 255, 255, 0.7)',
            '--glass-shadow': '0 5px 20px 0 rgba(14, 165, 233, 0.15)'
        }
    },
    {
        id: 'glass-amber',
        name: 'Amber Glass',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#451a03',
            '--bg-secondary': '#78350f',
            '--bg-tertiary': '#92400e',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#fef3c7',
            '--text-secondary': '#fde68a',
            '--text-tertiary': '#fbbf24',
            '--accent-primary': '#f59e0b',
            '--accent-secondary': '#fbbf24',
            '--border-color': 'rgba(245, 158, 11, 0.3)',
            '--glass-bg': 'rgba(69, 26, 3, 0.6)',
            '--glass-border': 'rgba(245, 158, 11, 0.2)',
            '--glass-shadow': '0 8px 30px 0 rgba(0, 0, 0, 0.5)'
        }
    },
    {
        id: 'glass-lavender',
        name: 'Lavender Mist',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#f5f3ff',
            '--bg-secondary': '#ede9fe',
            '--bg-tertiary': '#ddd6fe',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#4c1d95',
            '--text-secondary': '#6d28d9',
            '--text-tertiary': '#8b5cf6',
            '--accent-primary': '#7c3aed',
            '--accent-secondary': '#a78bfa',
            '--border-color': 'rgba(124, 58, 237, 0.2)',
            '--glass-bg': 'rgba(245, 243, 255, 0.65)',
            '--glass-border': 'rgba(255, 255, 255, 0.6)',
            '--glass-shadow': '0 4px 18px 0 rgba(124, 58, 237, 0.1)'
        }
    },
    {
        id: 'glass-emerald',
        name: 'Emerald City',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#022c22',
            '--bg-secondary': '#064e3b',
            '--bg-tertiary': '#065f46',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#ecfdf5',
            '--text-secondary': '#d1fae5',
            '--text-tertiary': '#6ee7b7',
            '--accent-primary': '#10b981',
            '--accent-secondary': '#34d399',
            '--border-color': 'rgba(16, 185, 129, 0.3)',
            '--glass-bg': 'rgba(2, 44, 34, 0.7)',
            '--glass-border': 'rgba(16, 185, 129, 0.2)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.5)'
        }
    },
    {
        id: 'glass-citrus',
        name: 'Citrus Splash',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#fefce8',
            '--bg-secondary': '#fef9c3',
            '--bg-tertiary': '#fef08a',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#713f12',
            '--text-secondary': '#854d0e',
            '--text-tertiary': '#a16207',
            '--accent-primary': '#eab308',
            '--accent-secondary': '#facc15',
            '--border-color': 'rgba(234, 179, 8, 0.2)',
            '--glass-bg': 'rgba(254, 252, 232, 0.6)',
            '--glass-border': 'rgba(255, 255, 255, 0.5)',
            '--glass-shadow': '0 4px 15px 0 rgba(234, 179, 8, 0.15)'
        }
    },
    {
        id: 'glass-crimson',
        name: 'Crimson Glass',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#450a0a',
            '--bg-secondary': '#7f1d1d',
            '--bg-tertiary': '#991b1b',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#fef2f2',
            '--text-secondary': '#fee2e2',
            '--text-tertiary': '#fca5a5',
            '--accent-primary': '#ef4444',
            '--accent-secondary': '#f87171',
            '--border-color': 'rgba(239, 68, 68, 0.3)',
            '--glass-bg': 'rgba(69, 10, 10, 0.6)',
            '--glass-border': 'rgba(239, 68, 68, 0.2)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.6)'
        }
    },
    {
        id: 'glass-sky',
        name: 'Open Sky',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#f0f9ff',
            '--bg-secondary': '#e0f2fe',
            '--bg-tertiary': '#bae6fd',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#075985',
            '--text-secondary': '#0369a1',
            '--text-tertiary': '#38bdf8',
            '--accent-primary': '#0ea5e9',
            '--accent-secondary': '#7dd3fc',
            '--border-color': 'rgba(14, 165, 233, 0.2)',
            '--glass-bg': 'rgba(240, 249, 255, 0.6)',
            '--glass-border': 'rgba(255, 255, 255, 0.6)',
            '--glass-shadow': '0 4px 15px 0 rgba(14, 165, 233, 0.15)'
        }
    },
    {
        id: 'glass-amethyst',
        name: 'Ultra Amethyst',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#2e1065',
            '--bg-secondary': '#4c1d95',
            '--bg-tertiary': '#5b21b6',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#f5f3ff',
            '--text-secondary': '#ddd6fe',
            '--text-tertiary': '#a78bfa',
            '--accent-primary': '#8b5cf6',
            '--accent-secondary': '#c4b5fd',
            '--border-color': 'rgba(139, 92, 246, 0.3)',
            '--glass-bg': 'rgba(46, 16, 101, 0.6)',
            '--glass-border': 'rgba(139, 92, 246, 0.2)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.5)'
        }
    },
    {
        id: 'glass-smoke',
        name: 'White Smoke',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#fafafa',
            '--bg-secondary': '#f4f4f5',
            '--bg-tertiary': '#e4e4e7',
            '--app-bg': 'linear-gradient(120deg, var(--bg-primary) 0%, var(--bg-tertiary) 100%)',
            '--text-primary': '#18181b',
            '--text-secondary': '#3f3f46',
            '--text-tertiary': '#a1a1aa',
            '--accent-primary': '#71717a',
            '--accent-secondary': '#a1a1aa',
            '--border-color': 'rgba(113, 113, 122, 0.2)',
            '--glass-bg': 'rgba(250, 250, 250, 0.5)',
            '--glass-border': 'rgba(255, 255, 255, 0.8)',
            '--glass-shadow': '0 4px 15px 0 rgba(0, 0, 0, 0.05)'
        }
    },
    {
        id: 'gen-crystal-glass',
        name: 'Diamond Crystal',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#f8e2f0',
            '--bg-secondary': '#f5d6ea',
            '--bg-tertiary': '#f2c9e3',
            '--text-primary': '#4a1236',
            '--text-secondary': '#9c2672',
            '--text-tertiary': '#d553a7',
            '--accent-primary': '#43c62f',
            '--accent-secondary': '#2fc6b2',
            '--border-color': '#f2c9e3',
            '--glass-bg': '#f8e2f099',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(135deg, #f8e2f0 0%, #f2c9e3 50%, #f5d6ea 100%)',
        },
    },
    {
        id: 'gen-prism-glass',
        name: 'Spectrum Prism',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#211a17',
            '--bg-secondary': '#302621',
            '--bg-tertiary': '#3f322c',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#37e6cf',
            '--accent-secondary': '#374ee6',
            '--border-color': '#3f322c',
            '--glass-bg': '#211a17b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(135deg, #211a17 0%, #3f322c 50%, #302621 100%)',
        },
    },
    {
        id: 'gen-lens-glass',
        name: 'Optical Lens',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f7f7f7',
            '--bg-tertiary': '#f0f0f0',
            '--text-primary': '#5c5e27',
            '--text-secondary': '#a3a645',
            '--text-tertiary': '#cacc85',
            '--accent-primary': '#618cbd',
            '--accent-secondary': '#9261bd',
            '--border-color': '#f0f0f0',
            '--glass-bg': '#ffffff99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(135deg, #ffffff 0%, #f0f0f0 50%, #f7f7f7 100%)',
        },
    },
    {
        id: 'gen-mirror-glass',
        name: 'Polished Mirror',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#fcfefc',
            '--bg-secondary': '#f1faf1',
            '--bg-tertiary': '#e5f6e5',
            '--text-primary': '#315724',
            '--text-secondary': '#5a9f42',
            '--text-tertiary': '#91c97e',
            '--accent-primary': '#725aba',
            '--accent-secondary': '#ba5aa2',
            '--border-color': '#e5f6e5',
            '--glass-bg': '#fcfefc99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(135deg, #fcfefc 0%, #e5f6e5 50%, #f1faf1 100%)',
        },
    },
    {
        id: 'gen-shard-glass',
        name: 'Obsidian Shard',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#241a23',
            '--bg-secondary': '#332531',
            '--bg-tertiary': '#422f40',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#68c828',
            '--accent-secondary': '#28c888',
            '--border-color': '#422f40',
            '--glass-bg': '#241a23b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(135deg, #241a23 0%, #422f40 50%, #332531 100%)',
        },
    },
    {
        id: 'gen-frost-glass',
        name: 'Arctic Frost',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#0e110d',
            '--bg-secondary': '#1a1f18',
            '--bg-tertiary': '#262e23',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#5e27dd',
            '--accent-secondary': '#dd27a6',
            '--border-color': '#262e23',
            '--glass-bg': '#0e110db3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(135deg, #0e110d 0%, #262e23 50%, #1a1f18 100%)',
        },
    },
    {
        id: 'gen-dew-glass',
        name: 'Morning Dew',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#23151e',
            '--bg-secondary': '#331f2c',
            '--bg-tertiary': '#432839',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#4aed31',
            '--accent-secondary': '#31edd4',
            '--border-color': '#432839',
            '--glass-bg': '#23151eb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(135deg, #23151e 0%, #432839 50%, #331f2c 100%)',
        },
    },
    {
        id: 'gen-rain-glass',
        name: 'Midnight Rain',
        category: 'glass',
        isDark: true,
        colors: {
            '--bg-primary': '#262626',
            '--bg-secondary': '#333333',
            '--bg-tertiary': '#404040',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#cbd062',
            '--accent-secondary': '#62d067',
            '--border-color': '#404040',
            '--glass-bg': '#262626b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(135deg, #262626 0%, #404040 50%, #333333 100%)',
        },
    },
    {
        id: 'gen-ice-glass',
        name: 'Glacial Ice',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f7f7f7',
            '--bg-tertiary': '#f0f0f0',
            '--text-primary': '#2e701f',
            '--text-secondary': '#4fc035',
            '--text-tertiary': '#90dc7f',
            '--accent-primary': '#7e58d0',
            '--accent-secondary': '#d058aa',
            '--border-color': '#f0f0f0',
            '--glass-bg': '#ffffff99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(135deg, #ffffff 0%, #f0f0f0 50%, #f7f7f7 100%)',
        },
    },
    {
        id: 'gen-vapor-glass',
        name: 'Ethereal Vapor',
        category: 'glass',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f7f7f7',
            '--bg-tertiary': '#f0f0f0',
            '--text-primary': '#082a09',
            '--text-secondary': '#18801b',
            '--text-tertiary': '#29d52e',
            '--accent-primary': '#6b22aa',
            '--accent-secondary': '#aa2261',
            '--border-color': '#f0f0f0',
            '--glass-bg': '#ffffff99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(135deg, #ffffff 0%, #f0f0f0 50%, #f7f7f7 100%)',
        },
    }
]
