import type { IlytatTheme } from '../../types'

export const solidThemes: IlytatTheme[] = [
    {
        id: 'solid-pure-blue',
        name: 'Pure Blue',
        category: 'solid',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#eff6ff',
            '--bg-tertiary': '#dbeafe',
            '--app-bg': '#ffffff',
            '--text-primary': '#1e3a8a',
            '--text-secondary': '#1e40af',
            '--text-tertiary': '#1d4ed8',
            '--accent-primary': '#2563eb',
            '--accent-secondary': '#3b82f6',
            '--border-color': '#dbeafe',
            '--glass-bg': '#ffffff',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-matte-black',
        name: 'Matte Black',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#111111',
            '--bg-secondary': '#222222',
            '--bg-tertiary': '#333333',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#ffffff',
            '--text-secondary': '#cccccc',
            '--text-tertiary': '#999999',
            '--accent-primary': '#ffffff',
            '--accent-secondary': '#cccccc',
            '--border-color': '#333333',
            '--glass-bg': '#111111',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-flat-ui',
        name: 'Flat UI',
        category: 'solid',
        isDark: false,
        colors: {
            '--bg-primary': '#ecf0f1',
            '--bg-secondary': '#bdc3c7',
            '--bg-tertiary': '#95a5a6',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#2c3e50',
            '--text-secondary': '#34495e',
            '--text-tertiary': '#7f8c8d',
            '--accent-primary': '#e74c3c',
            '--accent-secondary': '#e67e22',
            '--border-color': '#bdc3c7',
            '--glass-bg': '#ecf0f1',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-dracula',
        name: 'Dracula Solid',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#282a36',
            '--bg-secondary': '#44475a',
            '--bg-tertiary': '#6272a4',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#f8f8f2',
            '--text-secondary': '#bd93f9',
            '--text-tertiary': '#ff79c6',
            '--accent-primary': '#bd93f9',
            '--accent-secondary': '#ff79c6',
            '--border-color': '#44475a',
            '--glass-bg': '#282a36',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-coral',
        name: 'Coral Reef',
        category: 'solid',
        isDark: false,
        colors: {
            '--bg-primary': '#fff5f2',
            '--bg-secondary': '#ffe4d6',
            '--bg-tertiary': '#ffccbc',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#bf360c',
            '--text-secondary': '#d84315',
            '--text-tertiary': '#e64a19',
            '--accent-primary': '#ff5722',
            '--accent-secondary': '#ff7043',
            '--border-color': '#ffccbc',
            '--glass-bg': '#fff5f2',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-nord',
        name: 'Nord Solid',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#2e3440',
            '--bg-secondary': '#3b4252',
            '--bg-tertiary': '#434c5e',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#eceff4',
            '--text-secondary': '#e5e9f0',
            '--text-tertiary': '#d8dee9',
            '--accent-primary': '#88c0d0',
            '--accent-secondary': '#81a1c1',
            '--border-color': '#434c5e',
            '--glass-bg': '#2e3440',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-paper',
        name: 'Paper',
        category: 'solid',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f3f3f3',
            '--bg-tertiary': '#eeeeee',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#333333',
            '--text-secondary': '#555555',
            '--text-tertiary': '#777777',
            '--accent-primary': '#2196f3',
            '--accent-secondary': '#64b5f6',
            '--border-color': '#e0e0e0',
            '--glass-bg': '#ffffff',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-deep-ocean',
        name: 'Deep Ocean',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#001f3f',
            '--bg-secondary': '#003366',
            '--bg-tertiary': '#004080',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#ffffff',
            '--text-secondary': '#cce0ff',
            '--text-tertiary': '#99c2ff',
            '--accent-primary': '#0074d9',
            '--accent-secondary': '#39cccc',
            '--border-color': '#003366',
            '--glass-bg': '#001f3f',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-lavender-blush',
        name: 'Lavender Blush',
        category: 'solid',
        isDark: false,
        colors: {
            '--bg-primary': '#fff0f5',
            '--bg-secondary': '#e6e6fa',
            '--bg-tertiary': '#d8bfd8',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#4b0082',
            '--text-secondary': '#800080',
            '--text-tertiary': '#ba55d3',
            '--accent-primary': '#da70d6',
            '--accent-secondary': '#dda0dd',
            '--border-color': '#d8bfd8',
            '--glass-bg': '#fff0f5',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-space-gray',
        name: 'Space Gray',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#3e3e3e',
            '--bg-secondary': '#4e4e4e',
            '--bg-tertiary': '#5e5e5e',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#ffffff',
            '--text-secondary': '#e0e0e0',
            '--text-tertiary': '#bdbdbd',
            '--accent-primary': '#9e9e9e',
            '--accent-secondary': '#757575',
            '--border-color': '#4e4e4e',
            '--glass-bg': '#3e3e3e',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-mustard',
        name: 'Mustard',
        category: 'solid',
        isDark: false,
        colors: {
            '--bg-primary': '#fff8e1',
            '--bg-secondary': '#ffecb3',
            '--bg-tertiary': '#ffe082',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#3e2723',
            '--text-secondary': '#5d4037',
            '--text-tertiary': '#795548',
            '--accent-primary': '#ffca28',
            '--accent-secondary': '#ffc107',
            '--border-color': '#ffe082',
            '--glass-bg': '#fff8e1',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-forest-green',
        name: 'Forest Green',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#1b5e20',
            '--bg-secondary': '#2e7d32',
            '--bg-tertiary': '#388e3c',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#e8f5e9',
            '--text-secondary': '#c8e6c9',
            '--text-tertiary': '#a5d6a7',
            '--accent-primary': '#4caf50',
            '--accent-secondary': '#66bb6a',
            '--border-color': '#2e7d32',
            '--glass-bg': '#1b5e20',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-indigo',
        name: 'Indigo Solid',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#1a237e',
            '--bg-secondary': '#283593',
            '--bg-tertiary': '#303f9f',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#e8eaf6',
            '--text-secondary': '#c5cae9',
            '--text-tertiary': '#9fa8da',
            '--accent-primary': '#3f51b5',
            '--accent-secondary': '#5c6bc0',
            '--border-color': '#283593',
            '--glass-bg': '#1a237e',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-maroon',
        name: 'Maroon Solid',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#4a0000',
            '--bg-secondary': '#660000',
            '--bg-tertiary': '#800000',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#ffe6e6',
            '--text-secondary': '#ffcccc',
            '--text-tertiary': '#ffb3b3',
            '--accent-primary': '#ff0000',
            '--accent-secondary': '#cc0000',
            '--border-color': '#660000',
            '--glass-bg': '#4a0000',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'solid-teal',
        name: 'Teal Solid',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#004d40',
            '--bg-secondary': '#00695c',
            '--bg-tertiary': '#00796b',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#e0f2f1',
            '--text-secondary': '#b2dfdb',
            '--text-tertiary': '#80cbc4',
            '--accent-primary': '#009688',
            '--accent-secondary': '#26a69a',
            '--border-color': '#00695c',
            '--glass-bg': '#004d40',
            '--glass-border': 'transparent',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'gen-crimson-solid',
        name: 'Royal Crimson',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#242424',
            '--bg-secondary': '#313131',
            '--bg-tertiary': '#3e3e3e',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#acd25b',
            '--accent-secondary': '#5bd281',
            '--border-color': '#3e3e3e',
            '--glass-bg': '#242424b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#242424',
        },
    },
    {
        id: 'gen-azure-solid',
        name: 'Deep Azure',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#141414',
            '--bg-secondary': '#212121',
            '--bg-tertiary': '#2e2e2e',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#9c3c9f',
            '--accent-secondary': '#9f3c3f',
            '--border-color': '#2e2e2e',
            '--glass-bg': '#141414b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#141414',
        },
    },
    {
        id: 'gen-slate-solid',
        name: 'Graphite Slate',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#171717',
            '--bg-secondary': '#242424',
            '--bg-tertiary': '#313131',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#50c354',
            '--accent-secondary': '#50bfc3',
            '--border-color': '#313131',
            '--glass-bg': '#171717b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#171717',
        },
    },
    {
        id: 'gen-khaki-solid',
        name: 'Desert Khaki',
        category: 'solid',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f7f7f7',
            '--bg-tertiary': '#f0f0f0',
            '--text-primary': '#06214b',
            '--text-secondary': '#0e4ba9',
            '--text-tertiary': '#2f7aee',
            '--accent-primary': '#da2810',
            '--accent-secondary': '#c2da10',
            '--border-color': '#f0f0f0',
            '--glass-bg': '#ffffff99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': '#ffffff',
        },
    },
    {
        id: 'gen-olive-solid',
        name: 'Safari Olive',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#11120d',
            '--bg-secondary': '#1f2118',
            '--bg-tertiary': '#2d3022',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#233faf',
            '--accent-secondary': '#9323af',
            '--border-color': '#2d3022',
            '--glass-bg': '#11120db3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#11120d',
        },
    },
    {
        id: 'gen-mauve-solid',
        name: 'Twilight Mauve',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#20231a',
            '--bg-secondary': '#2d3225',
            '--bg-tertiary': '#3b4030',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#3f4fe4',
            '--accent-secondary': '#d43fe4',
            '--border-color': '#3b4030',
            '--glass-bg': '#20231ab3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#20231a',
        },
    },
    {
        id: 'gen-taupe-solid',
        name: 'Sandstone Taupe',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#121212',
            '--bg-secondary': '#1f1f1f',
            '--bg-tertiary': '#2c2c2c',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#4cacbd',
            '--accent-secondary': '#5d4cbd',
            '--border-color': '#2c2c2c',
            '--glass-bg': '#121212b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#121212',
        },
    },
    {
        id: 'gen-cyan-solid',
        name: 'Arctic Cyan',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#1e1a1c',
            '--bg-secondary': '#2c2629',
            '--bg-tertiary': '#393235',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#43db57',
            '--accent-secondary': '#43c7db',
            '--border-color': '#393235',
            '--glass-bg': '#1e1a1cb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#1e1a1c',
        },
    },
    {
        id: 'gen-lime-solid',
        name: 'Electric Lime',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#12150f',
            '--bg-secondary': '#1f241a',
            '--bg-tertiary': '#2c3324',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#2334b3',
            '--accent-secondary': '#a223b3',
            '--border-color': '#2c3324',
            '--glass-bg': '#12150fb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#12150f',
        },
    },
    {
        id: 'gen-denim-solid',
        name: 'Raw Denim',
        category: 'solid',
        isDark: true,
        colors: {
            '--bg-primary': '#121212',
            '--bg-secondary': '#1f1f1f',
            '--bg-tertiary': '#2c2c2c',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#399d86',
            '--accent-secondary': '#39509d',
            '--border-color': '#2c2c2c',
            '--glass-bg': '#121212b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': '#121212',
        },
    }
]
