import type { IlytatTheme } from '../../types'

export const cybersecurityThemes: IlytatTheme[] = [
    {
        id: 'cyberpunk-neon-city',
        name: 'Neon City',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#0b0c15',
            '--bg-secondary': '#161b22',
            '--bg-tertiary': '#21262d',
            '--app-bg': 'linear-gradient(to bottom right, #000000, #0c4a6e)', // Dark neon gradient
            '--text-primary': '#c9d1d9',
            '--text-secondary': '#8b949e',
            '--text-tertiary': '#6e7681',
            '--accent-primary': '#f0883e', // Orange neon
            '--accent-secondary': '#db6d28',
            '--border-color': '#30363d',
            '--glass-bg': 'rgba(11, 12, 21, 0.8)',
            '--glass-border': 'rgba(240, 136, 62, 0.3)',
            '--glass-shadow': '0 0 10px rgba(240, 136, 62, 0.2)'
        }
    },
    {
        id: 'cyberpunk-synthwave',
        name: 'Synthwave',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#241235',
            '--bg-secondary': '#411e58',
            '--bg-tertiary': '#632b7d',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#f7f1ff',
            '--text-secondary': '#d8b4fe',
            '--text-tertiary': '#c084fc',
            '--accent-primary': '#e879f9', // Pink neon
            '--accent-secondary': '#d946ef',
            '--border-color': '#581c87',
            '--glass-bg': 'rgba(36, 18, 53, 0.8)',
            '--glass-border': 'rgba(232, 121, 249, 0.3)',
            '--glass-shadow': '0 0 15px rgba(232, 121, 249, 0.2)'
        }
    },
    {
        id: 'cyberpunk-matrix',
        name: 'The Matrix',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#000000',
            '--bg-secondary': '#0a1a0f',
            '--bg-tertiary': '#143320',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#4ade80',
            '--text-secondary': '#22c55e',
            '--text-tertiary': '#16a34a',
            '--accent-primary': '#22c55e', // Green neon
            '--accent-secondary': '#15803d',
            '--border-color': '#14532d',
            '--glass-bg': 'rgba(0, 0, 0, 0.9)',
            '--glass-border': 'rgba(34, 197, 94, 0.4)',
            '--glass-shadow': '0 0 10px rgba(34, 197, 94, 0.2)'
        }
    },
    {
        id: 'cyberpunk-blade-runner',
        name: 'Blade Runner',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#0f172a',
            '--bg-secondary': '#1e293b',
            '--bg-tertiary': '#334155',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#f8fafc',
            '--text-secondary': '#cbd5e1',
            '--text-tertiary': '#94a3b8',
            '--accent-primary': '#ef4444', // Red neon
            '--accent-secondary': '#dc2626',
            '--border-color': '#334155',
            '--glass-bg': 'rgba(15, 23, 42, 0.85)',
            '--glass-border': 'rgba(239, 68, 68, 0.3)',
            '--glass-shadow': '0 0 12px rgba(239, 68, 68, 0.2)'
        }
    },
    {
        id: 'cyberpunk-netrunner',
        name: 'Netrunner',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#111827',
            '--bg-secondary': '#1f2937',
            '--bg-tertiary': '#374151',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#f3f4f6',
            '--text-secondary': '#d1d5db',
            '--text-tertiary': '#9ca3af',
            '--accent-primary': '#38bdf8', // Blue neon
            '--accent-secondary': '#0ea5e9',
            '--border-color': '#374151',
            '--glass-bg': 'rgba(17, 24, 39, 0.85)',
            '--glass-border': 'rgba(56, 189, 248, 0.3)',
            '--glass-shadow': '0 0 12px rgba(56, 189, 248, 0.2)'
        }
    },
    {
        id: 'cyberpunk-yellow-jacket',
        name: 'Yellow Jacket',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#1a1a1a',
            '--bg-secondary': '#2b2b2b',
            '--bg-tertiary': '#3d3d3d',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#ffff00',
            '--text-secondary': '#e6e600',
            '--text-tertiary': '#cccc00',
            '--accent-primary': '#ffff00', // Yellow
            '--accent-secondary': '#d4d400',
            '--border-color': '#4d4d00',
            '--glass-bg': 'rgba(26, 26, 26, 0.9)',
            '--glass-border': 'rgba(255, 255, 0, 0.4)',
            '--glass-shadow': '0 0 10px rgba(255, 255, 0, 0.2)'
        }
    },
    {
        id: 'cyberpunk-purple-haze',
        name: 'Purple Haze',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#2e1065',
            '--bg-secondary': '#4c1d95',
            '--bg-tertiary': '#5b21b6',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#f3e8ff',
            '--text-secondary': '#d8b4fe',
            '--text-tertiary': '#c084fc',
            '--accent-primary': '#d8b4fe', // Light Purple
            '--accent-secondary': '#a855f7',
            '--border-color': '#5b21b6',
            '--glass-bg': 'rgba(46, 16, 101, 0.8)',
            '--glass-border': 'rgba(216, 180, 254, 0.3)',
            '--glass-shadow': '0 0 15px rgba(216, 180, 254, 0.2)'
        }
    },
    {
        id: 'cyberpunk-electric-blue',
        name: 'Electric Blue',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#020617',
            '--bg-secondary': '#0f172a',
            '--bg-tertiary': '#1e293b',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#e0f2fe',
            '--text-secondary': '#7dd3fc',
            '--text-tertiary': '#38bdf8',
            '--accent-primary': '#00ffff', // Cyan
            '--accent-secondary': '#06b6d4',
            '--border-color': '#0891b2',
            '--glass-bg': 'rgba(2, 6, 23, 0.8)',
            '--glass-border': 'rgba(0, 255, 255, 0.3)',
            '--glass-shadow': '0 0 15px rgba(0, 255, 255, 0.2)'
        }
    },
    {
        id: 'cyberpunk-toxic-waste',
        name: 'Toxic Waste',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#1a2e05',
            '--bg-secondary': '#365314',
            '--bg-tertiary': '#4d7c0f',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#ecfccb',
            '--text-secondary': '#bef264',
            '--text-tertiary': '#a3e635',
            '--accent-primary': '#a3e635', // Lime
            '--accent-secondary': '#84cc16',
            '--border-color': '#4d7c0f',
            '--glass-bg': 'rgba(26, 46, 5, 0.85)',
            '--glass-border': 'rgba(163, 230, 53, 0.3)',
            '--glass-shadow': '0 0 12px rgba(163, 230, 53, 0.2)'
        }
    },
    {
        id: 'cyberpunk-hot-pink',
        name: 'Hot Pink',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#500724',
            '--bg-secondary': '#831843',
            '--bg-tertiary': '#9d174d',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#fbcfe8',
            '--text-secondary': '#f9a8d4',
            '--text-tertiary': '#f472b6',
            '--accent-primary': '#ff00ff', // Magenta
            '--accent-secondary': '#db2777',
            '--border-color': '#9d174d',
            '--glass-bg': 'rgba(80, 7, 36, 0.85)',
            '--glass-border': 'rgba(255, 0, 255, 0.3)',
            '--glass-shadow': '0 0 15px rgba(255, 0, 255, 0.2)'
        }
    },
    {
        id: 'cyberpunk-orange-crush',
        name: 'Orange Crush',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#431407',
            '--bg-secondary': '#7c2d12',
            '--bg-tertiary': '#9a3412',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#ffedd5',
            '--text-secondary': '#fdba74',
            '--text-tertiary': '#fb923c',
            '--accent-primary': '#f97316',
            '--accent-secondary': '#ea580c',
            '--border-color': '#9a3412',
            '--glass-bg': 'rgba(67, 20, 7, 0.85)',
            '--glass-border': 'rgba(249, 115, 22, 0.3)',
            '--glass-shadow': '0 0 12px rgba(249, 115, 22, 0.2)'
        }
    },
    {
        id: 'cyberpunk-deep-space',
        name: 'Deep Space',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#020205',
            '--bg-secondary': '#0a0a14',
            '--bg-tertiary': '#141428',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#e2e8f0',
            '--text-secondary': '#94a3b8',
            '--text-tertiary': '#64748b',
            '--accent-primary': '#818cf8',
            '--accent-secondary': '#6366f1',
            '--border-color': '#312e81',
            '--glass-bg': 'rgba(2, 2, 5, 0.9)',
            '--glass-border': 'rgba(129, 140, 248, 0.2)',
            '--glass-shadow': '0 0 15px rgba(129, 140, 248, 0.1)'
        }
    },
    {
        id: 'cyberpunk-glitch',
        name: 'Glitch',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#111',
            '--bg-secondary': '#222',
            '--bg-tertiary': '#333',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#eee',
            '--text-secondary': '#ccc',
            '--text-tertiary': '#aaa',
            '--accent-primary': '#ff0055',
            '--accent-secondary': '#00ff55',
            '--border-color': '#444',
            '--glass-bg': 'rgba(17, 17, 17, 0.9)',
            '--glass-border': 'rgba(255, 0, 85, 0.3)',
            '--glass-shadow': '2px 2px 0 rgba(0, 255, 85, 0.5)'
        }
    },
    {
        id: 'cyberpunk-data-stream',
        name: 'Data Stream',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#001a1a',
            '--bg-secondary': '#002b2b',
            '--bg-tertiary': '#004040',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#e0ffff',
            '--text-secondary': '#b3ffff',
            '--text-tertiary': '#80ffff',
            '--accent-primary': '#00ffff',
            '--accent-secondary': '#00cccc',
            '--border-color': '#004040',
            '--glass-bg': 'rgba(0, 26, 26, 0.85)',
            '--glass-border': 'rgba(0, 255, 255, 0.25)',
            '--glass-shadow': '0 0 10px rgba(0, 255, 255, 0.15)'
        }
    },
    {
        id: 'cyberpunk-red-alert',
        name: 'Red Alert',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#2b0000',
            '--bg-secondary': '#400000',
            '--bg-tertiary': '#600000',
            '--app-bg': 'linear-gradient(to bottom right, var(--bg-primary), var(--bg-tertiary))',
            '--text-primary': '#ffe0e0',
            '--text-secondary': '#ffb3b3',
            '--text-tertiary': '#ff8080',
            '--accent-primary': '#ff0000',
            '--accent-secondary': '#cc0000',
            '--border-color': '#800000',
            '--glass-bg': 'rgba(43, 0, 0, 0.9)',
            '--glass-border': 'rgba(255, 0, 0, 0.3)',
            '--glass-shadow': '0 0 15px rgba(255, 0, 0, 0.2)'
        }
    },
    {
        id: 'gen-neon-tokyo-cyberpunk',
        name: 'Neon Tokyo',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#201313',
            '--bg-secondary': '#351d16',
            '--bg-tertiary': '#4b2718',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#04fbf7',
            '--accent-secondary': '#0408fb',
            '--border-color': '#4b2718',
            '--glass-bg': '#201313b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #04fbf74d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #0408fb33 0%, transparent 25%), linear-gradient(180deg, #201313 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-circuit-cyberpunk',
        name: 'Circuit',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#1f0e1d',
            '--bg-secondary': '#331329',
            '--bg-tertiary': '#491737',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#26f906',
            '--accent-secondary': '#06f9d9',
            '--border-color': '#491737',
            '--glass-bg': '#1f0e1db3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #26f9064d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #06f9d933 0%, transparent 25%), linear-gradient(180deg, #1f0e1d 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-glitch-cyberpunk',
        name: 'Glitch',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#110d24',
            '--bg-secondary': '#161638',
            '--bg-tertiary': '#1a1d4e',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#fc3103',
            '--accent-secondary': '#cefc03',
            '--border-color': '#1a1d4e',
            '--glass-bg': '#110d24b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #fc31034d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #cefc0333 0%, transparent 25%), linear-gradient(180deg, #110d24 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-matrix-cyberpunk',
        name: 'Matrix',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#141d16',
            '--bg-secondary': '#1b321b',
            '--bg-tertiary': '#21481f',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#8800ff',
            '--accent-secondary': '#ff0077',
            '--border-color': '#21481f',
            '--glass-bg': '#141d16b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #8800ff4d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #ff007733 0%, transparent 25%), linear-gradient(180deg, #141d16 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-blade-cyberpunk',
        name: 'Blade',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#121b21',
            '--bg-secondary': '#192f32',
            '--bg-tertiary': '#1e4344',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#ed1299',
            '--accent-secondary': '#ed6612',
            '--border-color': '#1e4344',
            '--glass-bg': '#121b21b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #ed12994d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #ed661233 0%, transparent 25%), linear-gradient(180deg, #121b21 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-synth-cyberpunk',
        name: 'Synth',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#1e0e21',
            '--bg-secondary': '#311433',
            '--bg-tertiary': '#451846',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#71ec13',
            '--accent-secondary': '#13ec8e',
            '--border-color': '#451846',
            '--glass-bg': '#1e0e21b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #71ec134d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #13ec8e33 0%, transparent 25%), linear-gradient(180deg, #1e0e21 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-net-cyberpunk',
        name: 'Net',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#200d13',
            '--bg-secondary': '#341216',
            '--bg-tertiary': '#491618',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#0df269',
            '--accent-secondary': '#0d96f2',
            '--border-color': '#491618',
            '--glass-bg': '#200d13b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #0df2694d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #0d96f233 0%, transparent 25%), linear-gradient(180deg, #200d13 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-grid-cyberpunk',
        name: 'Grid',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#131c19',
            '--bg-secondary': '#193022',
            '--bg-tertiary': '#1f452a',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#d70df2',
            '--accent-secondary': '#f20d28',
            '--border-color': '#1f452a',
            '--glass-bg': '#131c19b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #d70df24d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #f20d2833 0%, transparent 25%), linear-gradient(180deg, #131c19 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-laser-cyberpunk',
        name: 'Laser',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#170a23',
            '--bg-secondary': '#211037',
            '--bg-tertiary': '#2d134b',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#eaf20d',
            '--accent-secondary': '#0df215',
            '--border-color': '#2d134b',
            '--glass-bg': '#170a23b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #eaf20d4d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #0df21533 0%, transparent 25%), linear-gradient(180deg, #170a23 0%, #000000 100%)',
        },
    },
    {
        id: 'gen-plasma-cyberpunk',
        name: 'Plasma',
        category: 'cyberpunk',
        isDark: true,
        colors: {
            '--bg-primary': '#121b1d',
            '--bg-secondary': '#192f2a',
            '--bg-tertiary': '#1e4438',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#ee11cd',
            '--accent-secondary': '#ee3211',
            '--border-color': '#1e4438',
            '--glass-bg': '#121b1db3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E"), radial-gradient(circle at 15% 50%, #ee11cd4d 0%, transparent 25%), radial-gradient(circle at 85% 30%, #ee321133 0%, transparent 25%), linear-gradient(180deg, #121b1d 0%, #000000 100%)',
        },
    }
]
