import type { IlytatTheme } from '../../types'

export const abstractThemes: IlytatTheme[] = [
    {
        id: 'abstract-pop-art',
        name: 'Pop Art',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#fef08a', // Yellow
            '--bg-tertiary': '#fca5a5', // Pink
            '--app-bg': '#ffffff',
            '--text-primary': '#000000',
            '--text-secondary': '#1e3a8a', // Blue
            '--text-tertiary': '#b91c1c', // Red
            '--accent-primary': '#ef4444',
            '--accent-secondary': '#3b82f6',
            '--border-color': '#000000',
            '--glass-bg': 'rgba(255, 255, 255, 0.9)',
            '--glass-border': '#000000',
            '--glass-shadow': '4px 4px 0 #000000'
        }
    },
    {
        id: 'abstract-monet',
        name: 'Impressionist',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#f0f9ff',
            '--bg-secondary': '#fdf2f8',
            '--bg-tertiary': '#f0fdf4',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#4c1d95',
            '--text-secondary': '#0f766e',
            '--text-tertiary': '#be185d',
            '--accent-primary': '#8b5cf6',
            '--accent-secondary': '#10b981',
            '--border-color': '#8b5cf6',
            '--glass-bg': 'rgba(240, 249, 255, 0.7)',
            '--glass-border': 'rgba(139, 92, 246, 0.2)',
            '--glass-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.05)'
        }
    },
    {
        id: 'abstract-bauhaus',
        name: 'Bauhaus',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#f3f4f6',
            '--bg-secondary': '#e5e7eb',
            '--bg-tertiary': '#d1d5db',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#111827',
            '--text-secondary': '#374151',
            '--text-tertiary': '#6b7280',
            '--accent-primary': '#dc2626', // Red
            '--accent-secondary': '#eab308', // Yellow
            '--border-color': '#1f2937',
            '--glass-bg': 'rgba(243, 244, 246, 0.95)',
            '--glass-border': '#1f2937',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'abstract-neon-night',
        name: 'Neon Dreams',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#1f1d24',
            '--bg-secondary': '#2e2a36',
            '--bg-tertiary': '#3f3a4d',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#fff',
            '--text-secondary': '#d1d5db',
            '--text-tertiary': '#9ca3af',
            '--accent-primary': '#00ffcc',
            '--accent-secondary': '#ff00cc',
            '--border-color': '#3f3a4d',
            '--glass-bg': 'rgba(31, 29, 36, 0.9)',
            '--glass-border': 'rgba(0, 255, 204, 0.3)',
            '--glass-shadow': '0 0 10px rgba(255, 0, 204, 0.2)'
        }
    },
    {
        id: 'abstract-pastel-dream',
        name: 'Pastel Dream',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#fff5f5',
            '--bg-secondary': '#fff0f0',
            '--bg-tertiary': '#ffe0e0',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#708090',
            '--text-secondary': '#a0b0c0',
            '--text-tertiary': '#c0d0e0',
            '--accent-primary': '#ffb6c1',
            '--accent-secondary': '#add8e6',
            '--border-color': '#ffe0e0',
            '--glass-bg': 'rgba(255, 245, 245, 0.8)',
            '--glass-border': 'rgba(255, 182, 193, 0.3)',
            '--glass-shadow': '0 2px 5px rgba(173, 216, 230, 0.2)'
        }
    },
    {
        id: 'abstract-midnight-oil',
        name: 'Midnight Oil',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#0c0c0c',
            '--bg-secondary': '#1a1a1a',
            '--bg-tertiary': '#262626',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#e0e0e0',
            '--text-secondary': '#b0b0b0',
            '--text-tertiary': '#808080',
            '--accent-primary': '#ff4500',
            '--accent-secondary': '#ffd700',
            '--border-color': '#262626',
            '--glass-bg': 'rgba(12, 12, 12, 0.9)',
            '--glass-border': 'rgba(255, 69, 0, 0.2)',
            '--glass-shadow': '0 0 10px rgba(255, 215, 0, 0.1)'

        }
    },
    {
        id: 'abstract-candy-crush',
        name: 'Candy Crush',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#fff0f5',
            '--bg-secondary': '#ffe4e1',
            '--bg-tertiary': '#ffc0cb',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#db7093',
            '--text-secondary': '#c71585',
            '--text-tertiary': '#ff69b4',
            '--accent-primary': '#ff1493',
            '--accent-secondary': '#ff6347',
            '--border-color': '#ffc0cb',
            '--glass-bg': 'rgba(255, 240, 245, 0.9)',
            '--glass-border': 'rgba(255, 20, 147, 0.2)',
            '--glass-shadow': '0 2px 8px rgba(255, 99, 71, 0.2)'
        }
    },
    {
        id: 'abstract-ocean-breeze',
        name: 'Ocean Breeze',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#e0ffff',
            '--bg-secondary': '#afeeee',
            '--bg-tertiary': '#40e0d0',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#008080',
            '--text-secondary': '#20b2aa',
            '--text-tertiary': '#48d1cc',
            '--accent-primary': '#00ced1',
            '--accent-secondary': '#5f9ea0',
            '--border-color': '#40e0d0',
            '--glass-bg': 'rgba(224, 255, 255, 0.8)',
            '--glass-border': 'rgba(0, 206, 209, 0.3)',
            '--glass-shadow': '0 2px 6px rgba(0, 128, 128, 0.1)'
        }
    },
    {
        id: 'abstract-twilight',
        name: 'Twilight Zone',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#2c3e50',
            '--bg-secondary': '#34495e',
            '--bg-tertiary': '#4a69bd',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#ecf0f1',
            '--text-secondary': '#bdc3c7',
            '--text-tertiary': '#95a5a6',
            '--accent-primary': '#e74c3c',
            '--accent-secondary': '#c0392b',
            '--border-color': '#34495e',
            '--glass-bg': 'rgba(44, 62, 80, 0.9)',
            '--glass-border': 'rgba(231, 76, 60, 0.2)',
            '--glass-shadow': '0 4px 10px rgba(0, 0, 0, 0.2)'
        }
    },
    {
        id: 'abstract-forest-fire',
        name: 'Forest Fire',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#1e272e',
            '--bg-secondary': '#303952',
            '--bg-tertiary': '#596275',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#f5f6fa',
            '--text-secondary': '#dcdde1',
            '--text-tertiary': '#7f8fa6',
            '--accent-primary': '#e15f41',
            '--accent-secondary': '#f7d794',
            '--border-color': '#303952',
            '--glass-bg': 'rgba(30, 39, 46, 0.95)',
            '--glass-border': 'rgba(225, 95, 65, 0.3)',
            '--glass-shadow': '0 4px 12px rgba(225, 95, 65, 0.1)'
        }
    },
    {
        id: 'abstract-retro-wave',
        name: 'Retro Wave',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#212121',
            '--bg-secondary': '#323232',
            '--bg-tertiary': '#424242',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#ffffff',
            '--text-secondary': '#cccccc',
            '--text-tertiary': '#999999',
            '--accent-primary': '#ff9f43',
            '--accent-secondary': '#ee5253',
            '--border-color': '#424242',
            '--glass-bg': 'rgba(33, 33, 33, 0.9)',
            '--glass-border': 'rgba(255, 159, 67, 0.3)',
            '--glass-shadow': '0 4px 10px rgba(255, 159, 67, 0.1)'
        }
    },
    {
        id: 'abstract-glacier',
        name: 'Glacier Melt',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#f8f9fa',
            '--bg-secondary': '#e9ecef',
            '--bg-tertiary': '#dee2e6',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#343a40',
            '--text-secondary': '#495057',
            '--text-tertiary': '#6c757d',
            '--accent-primary': '#00b4d8',
            '--accent-secondary': '#90e0ef',
            '--border-color': '#dee2e6',
            '--glass-bg': 'rgba(248, 249, 250, 0.85)',
            '--glass-border': 'rgba(0, 180, 216, 0.15)',
            '--glass-shadow': '0 2px 4px rgba(0, 180, 216, 0.05)'
        }
    },
    {
        id: 'abstract-amethyst-storm',
        name: 'Amethyst Storm',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#190028',
            '--bg-secondary': '#2e004b',
            '--bg-tertiary': '#48006e',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#e0b0ff',
            '--text-secondary': '#c586e0',
            '--text-tertiary': '#9a5cb5',
            '--accent-primary': '#bf00ff',
            '--accent-secondary': '#ea00d9',
            '--border-color': '#48006e',
            '--glass-bg': 'rgba(25, 0, 40, 0.9)',
            '--glass-border': 'rgba(191, 0, 255, 0.3)',
            '--glass-shadow': '0 0 12px rgba(191, 0, 255, 0.2)'
        }
    },
    {
        id: 'abstract-royal-blood',
        name: 'Royal Blood',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#1a0505',
            '--bg-secondary': '#330a0a',
            '--bg-tertiary': '#4d0f0f',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#d4af37', // Gold
            '--text-secondary': '#b3941f',
            '--text-tertiary': '#8c7310',
            '--accent-primary': '#ff0000',
            '--accent-secondary': '#800000',
            '--border-color': '#4d0f0f',
            '--glass-bg': 'rgba(26, 5, 5, 0.95)',
            '--glass-border': 'rgba(212, 175, 55, 0.2)',
            '--glass-shadow': '0 4px 10px rgba(212, 175, 55, 0.1)'
        }
    },
    {
        id: 'abstract-mint-chocolate',
        name: 'Mint Chocolate',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#262626',
            '--bg-secondary': '#333333',
            '--bg-tertiary': '#404040',
            '--app-bg': 'var(--bg-primary)',
            '--text-primary': '#98ff98', // Mint green
            '--text-secondary': '#7fb37f',
            '--text-tertiary': '#668c66',
            '--accent-primary': '#98ff98',
            '--accent-secondary': '#f0fff0',
            '--border-color': '#404040',
            '--glass-bg': 'rgba(38, 38, 38, 0.9)',
            '--glass-border': 'rgba(152, 255, 152, 0.2)',
            '--glass-shadow': '0 2px 5px rgba(152, 255, 152, 0.1)'
        }
    },
    {
        id: 'gen-chaos-abstract',
        name: 'Chaos',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#222226',
            '--bg-secondary': '#2e2e33',
            '--bg-tertiary': '#3a3a41',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#c27b38',
            '--accent-secondary': '#7fc238',
            '--border-color': '#3a3a41',
            '--glass-bg': '#222226b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(at 0% 0%, #c27b3826 0px, transparent 50%), radial-gradient(at 100% 0%, #7fc23826 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #222226 0%, #3a3a41 50%, #2e2e33 100%)',
        },
    },
    {
        id: 'gen-flux-abstract',
        name: 'Flux',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#171717',
            '--bg-secondary': '#242424',
            '--bg-tertiary': '#313131',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#5d46ce',
            '--accent-secondary': '#ce46b7',
            '--border-color': '#313131',
            '--glass-bg': '#171717b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(at 0% 0%, #5d46ce26 0px, transparent 50%), radial-gradient(at 100% 0%, #ce46b726 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #171717 0%, #313131 50%, #242424 100%)',
        },
    },
    {
        id: 'gen-void-abstract',
        name: 'Void',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#1e1e1e',
            '--bg-secondary': '#2b2b2b',
            '--bg-tertiary': '#373737',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#bf6377',
            '--accent-secondary': '#bfab63',
            '--border-color': '#373737',
            '--glass-bg': '#1e1e1eb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(at 0% 0%, #bf637726 0px, transparent 50%), radial-gradient(at 100% 0%, #bfab6326 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #1e1e1e 0%, #373737 50%, #2b2b2b 100%)',
        },
    },
    {
        id: 'gen-energy-abstract',
        name: 'Energy',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#1c1917',
            '--bg-secondary': '#2a2522',
            '--bg-tertiary': '#38322e',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#2eb898',
            '--accent-secondary': '#2e4eb8',
            '--border-color': '#38322e',
            '--glass-bg': '#1c1917b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(at 0% 0%, #2eb89826 0px, transparent 50%), radial-gradient(at 100% 0%, #2e4eb826 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #1c1917 0%, #38322e 50%, #2a2522 100%)',
        },
    },
    {
        id: 'gen-matter-abstract',
        name: 'Matter',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#0f0f0f',
            '--bg-secondary': '#1c1c1c',
            '--bg-tertiary': '#292929',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#863899',
            '--accent-secondary': '#99384b',
            '--border-color': '#292929',
            '--glass-bg': '#0f0f0fb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(at 0% 0%, #86389926 0px, transparent 50%), radial-gradient(at 100% 0%, #99384b26 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #0f0f0f 0%, #292929 50%, #1c1c1c 100%)',
        },
    },
    {
        id: 'gen-time-abstract',
        name: 'Time',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#fde3f5',
            '--bg-secondary': '#fcd5f0',
            '--bg-tertiary': '#fbc6eb',
            '--text-primary': '#5a0742',
            '--text-secondary': '#b90e87',
            '--text-tertiary': '#f03dbc',
            '--accent-primary': '#41e713',
            '--accent-secondary': '#13e7b9',
            '--border-color': '#fbc6eb',
            '--glass-bg': '#fde3f599',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'radial-gradient(at 0% 0%, #41e71326 0px, transparent 50%), radial-gradient(at 100% 0%, #13e7b926 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #fde3f5 0%, #fbc6eb 50%, #fcd5f0 100%)',
        },
    },
    {
        id: 'gen-space-abstract',
        name: 'Space',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f7f7f7',
            '--bg-tertiary': '#f0f0f0',
            '--text-primary': '#811317',
            '--text-secondary': '#da2027',
            '--text-tertiary': '#eb757a',
            '--accent-primary': '#49e491',
            '--accent-secondary': '#499ce4',
            '--border-color': '#f0f0f0',
            '--glass-bg': '#ffffff99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'radial-gradient(at 0% 0%, #49e49126 0px, transparent 50%), radial-gradient(at 100% 0%, #499ce426 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #ffffff 0%, #f0f0f0 50%, #f7f7f7 100%)',
        },
    },
    {
        id: 'gen-dream-abstract',
        name: 'Dream',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#0c1109',
            '--bg-secondary': '#182212',
            '--bg-tertiary': '#24321b',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#1b13b9',
            '--accent-secondary': '#b913b1',
            '--border-color': '#24321b',
            '--glass-bg': '#0c1109b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(at 0% 0%, #1b13b926 0px, transparent 50%), radial-gradient(at 100% 0%, #b913b126 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #0c1109 0%, #24321b 50%, #182212 100%)',
        },
    },
    {
        id: 'gen-nightmare-abstract',
        name: 'Nightmare',
        category: 'abstract',
        isDark: true,
        colors: {
            '--bg-primary': '#1a1a1f',
            '--bg-secondary': '#26262d',
            '--bg-tertiary': '#31313b',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#bb8830',
            '--accent-secondary': '#63bb30',
            '--border-color': '#31313b',
            '--glass-bg': '#1a1a1fb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'radial-gradient(at 0% 0%, #bb883026 0px, transparent 50%), radial-gradient(at 100% 0%, #63bb3026 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #1a1a1f 0%, #31313b 50%, #26262d 100%)',
        },
    },
    {
        id: 'gen-vision-abstract',
        name: 'Vision',
        category: 'abstract',
        isDark: false,
        colors: {
            '--bg-primary': '#d3f8f0',
            '--bg-secondary': '#c6f6ec',
            '--bg-tertiary': '#b9f4e7',
            '--text-primary': '#0b4136',
            '--text-secondary': '#1a987e',
            '--text-tertiary': '#3adebc',
            '--accent-primary': '#c52094',
            '--accent-secondary': '#c55120',
            '--border-color': '#b9f4e7',
            '--glass-bg': '#d3f8f099',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'radial-gradient(at 0% 0%, #c5209426 0px, transparent 50%), radial-gradient(at 100% 0%, #c5512026 0px, transparent 50%), conic-gradient(from 90deg at 50% 50%, #d3f8f0 0%, #b9f4e7 50%, #c6f6ec 100%)',
        },
    }
]
