import type { IlytatTheme } from '../../types'

export const natureThemes: IlytatTheme[] = [
    {
        id: 'nature-forest-morning',
        name: 'Forest Morning',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#f0fdf4',
            '--bg-secondary': '#dcfce7',
            '--bg-tertiary': '#bbf7d0',
            '--app-bg': 'linear-gradient(to top, #ecfdf5 0%, #f0fdf4 100%)', // Soft organic gradient
            '--text-primary': '#14532d',
            '--text-secondary': '#166534',
            '--text-tertiary': '#15803d',
            '--accent-primary': '#22c55e',
            '--accent-secondary': '#4ade80',
            '--border-color': '#86efac',
            '--glass-bg': 'rgba(240, 253, 244, 0.8)',
            '--glass-border': 'rgba(34, 197, 94, 0.2)',
            '--glass-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
        }
    },
    {
        id: 'nature-ocean-depths',
        name: 'Ocean Depths',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#0c4a6e',
            '--bg-secondary': '#075985',
            '--bg-tertiary': '#0369a1',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#f0f9ff',
            '--text-secondary': '#bae6fd',
            '--text-tertiary': '#7dd3fc',
            '--accent-primary': '#38bdf8',
            '--accent-secondary': '#0ea5e9',
            '--border-color': '#075985',
            '--glass-bg': 'rgba(12, 74, 110, 0.8)',
            '--glass-border': 'rgba(56, 189, 248, 0.2)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.3)'
        }
    },
    {
        id: 'nature-sunset-valley',
        name: 'Sunset Valley',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#fff7ed',
            '--bg-secondary': '#ffedd5',
            '--bg-tertiary': '#fed7aa',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#7c2d12',
            '--text-secondary': '#9a3412',
            '--text-tertiary': '#c2410c',
            '--accent-primary': '#f97316',
            '--accent-secondary': '#fb923c',
            '--border-color': '#fdba74',
            '--glass-bg': 'rgba(255, 247, 237, 0.8)',
            '--glass-border': 'rgba(249, 115, 22, 0.2)',
            '--glass-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
        }
    },
    {
        id: 'nature-desert-sands',
        name: 'Desert Sands',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#fdf2e9',
            '--bg-secondary': '#fae8d6',
            '--bg-tertiary': '#f3dcc3',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#5d4037',
            '--text-secondary': '#795548',
            '--text-tertiary': '#a1887f',
            '--accent-primary': '#d7ccc8',
            '--accent-secondary': '#efebe9',
            '--border-color': '#d7ccc8',
            '--glass-bg': 'rgba(253, 242, 233, 0.85)',
            '--glass-border': 'rgba(121, 85, 72, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'nature-mossy-rock',
        name: 'Mossy Rock',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#1c1917',
            '--bg-secondary': '#292524',
            '--bg-tertiary': '#44403c',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#d6d3d1',
            '--text-secondary': '#a8a29e',
            '--text-tertiary': '#78716c',
            '--accent-primary': '#84cc16', // Lime green accent
            '--accent-secondary': '#a3e635',
            '--border-color': '#44403c',
            '--glass-bg': 'rgba(28, 25, 23, 0.9)',
            '--glass-border': 'rgba(132, 204, 22, 0.2)',
            '--glass-shadow': '0 4px 6px rgba(0,0,0,0.3)'
        }
    },
    {
        id: 'nature-cherry-blossom',
        name: 'Cherry Blossom',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#fff1f2',
            '--bg-secondary': '#ffe4e6',
            '--bg-tertiary': '#fecdd3',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#881337',
            '--text-secondary': '#9f1239',
            '--text-tertiary': '#be123c',
            '--accent-primary': '#fb7185',
            '--accent-secondary': '#f43f5e',
            '--border-color': '#fecdd3',
            '--glass-bg': 'rgba(255, 241, 242, 0.8)',
            '--glass-border': 'rgba(251, 113, 133, 0.2)',
            '--glass-shadow': '0 2px 4px rgba(251, 113, 133, 0.1)'
        }
    },
    {
        id: 'nature-autumn-leaves',
        name: 'Autumn Leaves',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#451a03',
            '--bg-secondary': '#78350f',
            '--bg-tertiary': '#92400e',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#fef3c7',
            '--text-secondary': '#fde68a',
            '--text-tertiary': '#fbbf24',
            '--accent-primary': '#f59e0b',
            '--accent-secondary': '#d97706',
            '--border-color': '#92400e',
            '--glass-bg': 'rgba(69, 26, 3, 0.9)',
            '--glass-border': 'rgba(245, 158, 11, 0.2)',
            '--glass-shadow': '0 4px 10px rgba(0,0,0,0.5)'
        }
    },
    {
        id: 'nature-stormy-sky',
        name: 'Stormy Sky',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#374151',
            '--bg-secondary': '#4b5563',
            '--bg-tertiary': '#6b7280',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#f9fafb',
            '--text-secondary': '#e5e7eb',
            '--text-tertiary': '#d1d5db',
            '--accent-primary': '#fbbf24', // Lightning yellow
            '--accent-secondary': '#f59e0b',
            '--border-color': '#4b5563',
            '--glass-bg': 'rgba(55, 65, 81, 0.9)',
            '--glass-border': 'rgba(251, 191, 36, 0.3)',
            '--glass-shadow': '0 4px 12px rgba(0,0,0,0.4)'
        }
    },
    {
        id: 'nature-lilac-field',
        name: 'Lilac Field',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#faf5ff',
            '--bg-secondary': '#f3e8ff',
            '--bg-tertiary': '#e9d5ff',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#581c87',
            '--text-secondary': '#6b21a8',
            '--text-tertiary': '#7e22ce',
            '--accent-primary': '#a855f7',
            '--accent-secondary': '#c084fc',
            '--border-color': '#e9d5ff',
            '--glass-bg': 'rgba(250, 245, 255, 0.85)',
            '--glass-border': 'rgba(168, 85, 247, 0.15)',
            '--glass-shadow': '0 2px 8px rgba(168, 85, 247, 0.05)'
        }
    },
    {
        id: 'nature-river-stone',
        name: 'River Stone',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#f5f5f4',
            '--bg-secondary': '#e7e5e4',
            '--bg-tertiary': '#d6d3d1',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#44403c',
            '--text-secondary': '#57534e',
            '--text-tertiary': '#78716c',
            '--accent-primary': '#0ea5e9', // Water blue
            '--accent-secondary': '#38bdf8',
            '--border-color': '#d6d3d1',
            '--glass-bg': 'rgba(245, 245, 244, 0.9)',
            '--glass-border': 'rgba(14, 165, 233, 0.1)',
            '--glass-shadow': '0 2px 4px rgba(0,0,0,0.05)'
        }
    },
    {
        id: 'nature-bamboo',
        name: 'Bamboo Grove',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#f0fdf4',
            '--bg-secondary': '#dcfce7',
            '--bg-tertiary': '#bbf7d0',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#14532d',
            '--text-secondary': '#166534',
            '--text-tertiary': '#22c55e',
            '--accent-primary': '#84cc16',
            '--accent-secondary': '#a3e635',
            '--border-color': '#bbf7d0',
            '--glass-bg': 'rgba(240, 253, 244, 0.85)',
            '--glass-border': 'rgba(20, 83, 45, 0.1)',
            '--glass-shadow': 'none'
        }
    },
    {
        id: 'nature-polar-night',
        name: 'Polar Night',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#2e3440',
            '--bg-secondary': '#3b4252',
            '--bg-tertiary': '#434c5e',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#eceff4',
            '--text-secondary': '#e5e9f0',
            '--text-tertiary': '#d8dee9',
            '--accent-primary': '#88c0d0',
            '--accent-secondary': '#81a1c1',
            '--border-color': '#4c566a',
            '--glass-bg': 'rgba(46, 52, 64, 0.9)',
            '--glass-border': 'rgba(136, 192, 208, 0.2)',
            '--glass-shadow': '0 4px 10px rgba(0,0,0,0.3)'
        }
    },
    {
        id: 'nature-sunflower',
        name: 'Sunflower Field',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#fefce8',
            '--bg-secondary': '#fef9c3',
            '--bg-tertiary': '#fef08a',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#422006',
            '--text-secondary': '#713f12',
            '--text-tertiary': '#854d0e',
            '--accent-primary': '#eab308',
            '--accent-secondary': '#facc15',
            '--border-color': '#fef08a',
            '--glass-bg': 'rgba(254, 252, 232, 0.9)',
            '--glass-border': 'rgba(234, 179, 8, 0.15)',
            '--glass-shadow': '0 2px 5px rgba(234, 179, 8, 0.05)'
        }
    },
    {
        id: 'nature-volcanic',
        name: 'Volcanic Ash',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#18181b',
            '--bg-secondary': '#27272a',
            '--bg-tertiary': '#3f3f46',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#fafafa',
            '--text-secondary': '#d4d4d8',
            '--text-tertiary': '#a1a1aa',
            '--accent-primary': '#ef4444', // Magma red
            '--accent-secondary': '#f87171',
            '--border-color': '#27272a',
            '--glass-bg': 'rgba(24, 24, 27, 0.95)',
            '--glass-border': 'rgba(239, 68, 68, 0.2)',
            '--glass-shadow': '0 4px 15px rgba(239, 68, 68, 0.1)'
        }
    },
    {
        id: 'nature-blue-lagoon',
        name: 'Blue Lagoon',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#ecfeff',
            '--bg-secondary': '#cffafe',
            '--bg-tertiary': '#a5f3fc',
            '--app-bg': 'linear-gradient(to top, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
            '--text-primary': '#164e63',
            '--text-secondary': '#155e75',
            '--text-tertiary': '#0e7490',
            '--accent-primary': '#06b6d4',
            '--accent-secondary': '#22d3ee',
            '--border-color': '#a5f3fc',
            '--glass-bg': 'rgba(236, 254, 255, 0.8)',
            '--glass-border': 'rgba(6, 182, 212, 0.2)',
            '--glass-shadow': '0 4px 8px rgba(6, 182, 212, 0.1)'
        }
    },
    {
        id: 'gen-moss-nature',
        name: 'Verdant Moss',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#dde8ed',
            '--bg-secondary': '#d3e1e8',
            '--bg-tertiary': '#c9dae2',
            '--text-primary': '#1a2a32',
            '--text-secondary': '#3d6275',
            '--text-tertiary': '#6898b0',
            '--accent-primary': '#964f5c',
            '--accent-secondary': '#96894f',
            '--border-color': '#c9dae2',
            '--glass-bg': '#dde8ed99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(to bottom, #c9dae2, #dde8ed), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.04\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-fern-nature',
        name: 'Silver Fern',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#f5f2eb',
            '--bg-secondary': '#f0ebe1',
            '--bg-tertiary': '#ebe5d7',
            '--text-primary': '#403821',
            '--text-secondary': '#837344',
            '--text-tertiary': '#b8a775',
            '--accent-primary': '#5691a4',
            '--accent-secondary': '#6a56a4',
            '--border-color': '#ebe5d7',
            '--glass-bg': '#f5f2eb99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(to bottom, #ebe5d7, #f5f2eb), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.04\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-bark-nature',
        name: 'Ancient Bark',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#1c1c1c',
            '--bg-secondary': '#292929',
            '--bg-tertiary': '#363636',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#60beb6',
            '--accent-secondary': '#6068be',
            '--border-color': '#363636',
            '--glass-bg': '#1c1c1cb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(to bottom, #363636, #1c1c1c), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-leaf-nature',
        name: 'Autumn Leaf',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#242424',
            '--bg-secondary': '#313131',
            '--bg-tertiary': '#3e3e3e',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#60b2cd',
            '--accent-secondary': '#7b60cd',
            '--border-color': '#3e3e3e',
            '--glass-bg': '#242424b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(to bottom, #3e3e3e, #242424), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-petal-nature',
        name: 'Midnight Petal',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#110f0e',
            '--bg-secondary': '#1f1b1a',
            '--bg-tertiary': '#2d2825',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#2bdacb',
            '--accent-secondary': '#2b3ada',
            '--border-color': '#2d2825',
            '--glass-bg': '#110f0eb3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(to bottom, #2d2825, #110f0e), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-root-nature',
        name: 'Earthy Root',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f7f7f7',
            '--bg-tertiary': '#f0f0f0',
            '--text-primary': '#020303',
            '--text-secondary': '#2b4040',
            '--text-tertiary': '#547d7d',
            '--accent-primary': '#69353e',
            '--accent-secondary': '#696035',
            '--border-color': '#f0f0f0',
            '--glass-bg': '#ffffff99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(to bottom, #f0f0f0, #ffffff), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.04\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-soil-nature',
        name: 'Deep Soil',
        category: 'nature',
        isDark: false,
        colors: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f7f7f7',
            '--bg-tertiary': '#f0f0f0',
            '--text-primary': '#061906',
            '--text-secondary': '#1a6b1a',
            '--text-tertiary': '#2dbe2d',
            '--accent-primary': '#5c2494',
            '--accent-secondary': '#94245c',
            '--border-color': '#f0f0f0',
            '--glass-bg': '#ffffff99',
            '--glass-border': 'rgba(255,255,255,0.6)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
            '--app-bg': 'linear-gradient(to bottom, #f0f0f0, #ffffff), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.04\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-river-nature',
        name: 'Glacial River',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#000000',
            '--bg-secondary': '#0d0d0d',
            '--bg-tertiary': '#1a1a1a',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#541d8b',
            '--accent-secondary': '#8b1d54',
            '--border-color': '#1a1a1a',
            '--glass-bg': '#000000b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(to bottom, #1a1a1a, #000000), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-lake-nature',
        name: 'Alpine Lake',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#000000',
            '--bg-secondary': '#0d0d0d',
            '--bg-tertiary': '#1a1a1a',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#68313a',
            '--accent-secondary': '#685f31',
            '--border-color': '#1a1a1a',
            '--glass-bg': '#000000b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(to bottom, #1a1a1a, #000000), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    },
    {
        id: 'gen-peak-nature',
        name: 'Obsidian Peak',
        category: 'nature',
        isDark: true,
        colors: {
            '--bg-primary': '#242424',
            '--bg-secondary': '#313131',
            '--bg-tertiary': '#3e3e3e',
            '--text-primary': '#ffffff',
            '--text-secondary': '#ffffffcc',
            '--text-tertiary': '#ffffff80',
            '--accent-primary': '#b97480',
            '--accent-secondary': '#b9ad74',
            '--border-color': '#3e3e3e',
            '--glass-bg': '#242424b3',
            '--glass-border': 'rgba(255,255,255,0.1)',
            '--glass-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
            '--app-bg': 'linear-gradient(to bottom, #3e3e3e, #242424), url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")',
        },
    }
]
